name: Cloudhub deploy to Dev
# Controls when the workflow will run
on:
  pull_request:
    branches: [main]
    types: [closed] 

jobs:

  buildAndPublishToExchange:
    #needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: dev
    - name: Bump patch version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        PATCH=$(echo $VERSION | awk -F. '{print $3}')
        MINOR=$(echo $VERSION | awk -F. '{print $2}')
        MAJOR=$(echo $VERSION | awk -F. '{print $1}')
        NEW_PATCH=$((PATCH+1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add pom.xml
        git commit -m "ci: bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
        git push origin HEAD:dev || echo "No changes to push"
    # - name: Cache dependencies
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.m2/repository
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-maven-
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     distribution: 'zulu'
    #     java-version: 17
    # - name: Build with Maven
    #   env:
    #     CONTD_APP_CLIENT_ID: ${{ secrets.CONTD_APP_CLIENT_ID }}
    #     CONTD_APP_CLIENT_SECRET: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
    #     ORG_ID: ${{ secrets.MULE_ORG_ID }}
    #     environment: "Dev"
    #     target: "non-prod-mule-private-space"
    #     replicas: "1"
    #     cores: "0.1"
    #     KEY: ${{ secrets.ENCRYPT_KEY_DEV }}
    #     ANYPOINT_PLATFORM_CLIENT_ID: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}
    #     ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
    #     NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
    #     NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    #   run: mvn clean -B deploy -DskipMunitTests -s .maven/settings.xml

