name: M pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Build with Maven
        run: mvn clean package

      - name: Build hello-world application with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

      - name: Get NPM
        run: npm install -g anypoint-cli@latest
      - name: run anypoint-cli
        run: anypoint-cli --username=$AP_USERNAME --password=$AP_PASSWORD --environment=DEVELOPMENT runtime-mgr cloudhub-application modify pipeline-testing /target/pipeline-testing-1.0.0-SNAPSHOT-mule-application.jar
